# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  shared_config = debug
  GameRuntime_config = debug
  Editor_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  shared_config = release
  GameRuntime_config = release
  Editor_config = release
  Sandbox_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := shared GameRuntime Editor Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

shared:
ifneq (,$(shared_config))
	@echo "==== Building shared ($(shared_config)) ===="
	@${MAKE} --no-print-directory -C buildscripts -f shared.make config=$(shared_config)
endif

GameRuntime: shared
ifneq (,$(GameRuntime_config))
	@echo "==== Building GameRuntime ($(GameRuntime_config)) ===="
	@${MAKE} --no-print-directory -C buildscripts -f GameRuntime.make config=$(GameRuntime_config)
endif

Editor: shared
ifneq (,$(Editor_config))
	@echo "==== Building Editor ($(Editor_config)) ===="
	@${MAKE} --no-print-directory -C buildscripts -f Editor.make config=$(Editor_config)
endif

Sandbox: shared
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C buildscripts -f Sandbox.make config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C buildscripts -f shared.make clean
	@${MAKE} --no-print-directory -C buildscripts -f GameRuntime.make clean
	@${MAKE} --no-print-directory -C buildscripts -f Editor.make clean
	@${MAKE} --no-print-directory -C buildscripts -f Sandbox.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   shared"
	@echo "   GameRuntime"
	@echo "   Editor"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"