# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GameRuntime_config = debug
  Editor_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  GameRuntime_config = release
  Editor_config = release
  Sandbox_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GameRuntime Editor Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GameRuntime:
ifneq (,$(GameRuntime_config))
	@echo "==== Building GameRuntime ($(GameRuntime_config)) ===="
	@${MAKE} --no-print-directory -C . -f GameRuntime.make config=$(GameRuntime_config)
endif

Editor:
ifneq (,$(Editor_config))
	@echo "==== Building Editor ($(Editor_config)) ===="
	@${MAKE} --no-print-directory -C . -f Editor.make config=$(Editor_config)
endif

Sandbox:
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C . -f Sandbox.make config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f GameRuntime.make clean
	@${MAKE} --no-print-directory -C . -f Editor.make clean
	@${MAKE} --no-print-directory -C . -f Sandbox.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GameRuntime"
	@echo "   Editor"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"